# Generated by Django 4.0 on 2022-01-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_doctorhospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorhospital',
            old_name='Location',
            new_name='Experience',
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctorhospital',
            name='phone_no',
            field=models.CharField(max_length=25),
        ),
    ]
