# Generated by Django 4.0 on 2022-01-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_alter_doctorhospital_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorhospital',
            options={'ordering': ('-experience',)},
        ),
        migrations.AddField(
            model_name='doctorhospital',
            name='qualification',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
