# Generated by Django 4.0 on 2022-01-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_alter_doctorhospital_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
