# Generated by Django 4.0 on 2022-01-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorhospital',
            name='casesHandle',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
